from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Dict, List, Optional


@dataclass(frozen=True)
class ObjectCard:
    key: str
    title: str
    role: str
    definition: str
    derivation: str
    implementation: str
    test: str
    status: str
    interpretation: str
    docs: List[str] = field(default_factory=list)
    crossrefs: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, object]:
        return asdict(self)


OBJECT_CARDS: Dict[str, ObjectCard] = {
    'identity': ObjectCard(
        key='identity',
        title='Identity Attractor',
        role='Central organizing state of the Omega cockpit and its active relational configuration.',
        definition='The identity attractor is the center that keeps export state, ethics, memory, resonance, and operational coherence readable as one system.',
        derivation='Derived from the attractor-centered cockpit architecture where system geometry is organized around relation and identity rather than peer runtime tabs.',
        implementation='Rendered in main.apps.omega_orbital_app with identity snapshot, inspector state, event strip, and runtime anchors.',
        test='Check root workspace load, identity snapshot population, and inspector payload consistency.',
        status='runtime-only',
        interpretation='This is not chat or a model. It is the operational center of coherence for the current Omega surface.',
        docs=['docs/OMEGA_COCKPIT_1_0.md', 'docs/OBJECT_CARDS.md'],
        crossrefs=['theory', 'execution', 'memory_topology', 'boundary'],
    ),
    'theory': ObjectCard(
        key='theory',
        title='Theory Interface',
        role='Formal entry layer for axioms, definitions, derivations, and structured concepts.',
        definition='Theory is the constitutive layer from which operators, constants, constraints, and memory topology derive their formal status.',
        derivation='Follows the workflow Axiom -> Definition -> Derivation -> Implementation -> Test -> Status -> Interpretation.',
        implementation='Represented as a constitutive orbit in main.apps.orbital_cockpit and surfaced in the orbital app workspace.',
        test='Verify navigation, object card rendering, and manifest export for the constitutive orbit.',
        status='provisional',
        interpretation='Theory is the source layer that gives meaning and structure to the rest of the cockpit.',
        docs=['docs/OMEGA_COCKPIT_1_0.md', 'docs/OBJECT_CARDS.md'],
        crossrefs=['operators', 'constants', 'constraints', 'memory_topology', 'analogies'],
    ),
    'operators': ObjectCard(
        key='operators',
        title='Operators',
        role='Bridge formal theory to executable or inspectable actions.',
        definition='Operators are exported formal actions, couplings, or transformations that can later be bound to runtime behavior.',
        derivation='Operators arise from the theory layer and are linked by white threads to execution and kernel layers.',
        implementation='Tracked as constitutive nodes and cross-linked to kernel logic and future object manifests.',
        test='Verify navigation and manifest coverage; later bind to explicit code paths and tests.',
        status='provisional',
        interpretation='Operators are where abstract structure begins to become actionable.',
        docs=['docs/OMEGA_COCKPIT_1_0.md'],
        crossrefs=['theory', 'kernel', 'execution'],
    ),
    'constants': ObjectCard(
        key='constants',
        title='Constants',
        role='Hold active constant sets and runtime-imported parameter values.',
        definition='Constants are stable values or named parameter bundles used by the cockpit and runtime.',
        derivation='They are exposed as constitutive nodes because execution depends on them but does not define them.',
        implementation='Surfaced in topology, manifest export, and object card registry; later bind to explicit exported constant sets.',
        test='Confirm visibility in navigation, manifest, and inspector.',
        status='runtime-only',
        interpretation='Constants are the stable anchors that prevent the runtime from becoming semantically shapeless.',
        docs=['docs/OMEGA_COCKPIT_1_0.md'],
        crossrefs=['theory', 'kernel', 'constraints'],
    ),
    'constraints': ObjectCard(
        key='constraints',
        title='Constraints',
        role='Limit valid motion and preserve coherent state-space boundaries.',
        definition='Constraints define what counts as a valid path, state, or transformation inside the Omega cockpit.',
        derivation='They are formalized as constitutive conditions and linked to execution by bounding white threads.',
        implementation='Currently represented in topology and object cards; later should map to explicit runtime and publication checks.',
        test='Verify object-card rendering and manifest inclusion; later bind to real validations.',
        status='provisional',
        interpretation='Constraints do not kill freedom; they shape meaningful possibility.',
        docs=['docs/OMEGA_COCKPIT_1_0.md', 'docs/analogies/MNEMONIC_BOOK_FOR_KIDS.md'],
        crossrefs=['theory', 'execution', 'boundary', 'tests'],
    ),
    'memory_topology': ObjectCard(
        key='memory_topology',
        title='Memory Topology',
        role='Represent the structured arrangement of memory channels and dependencies.',
        definition='Memory topology is the pattern of relational memory rather than mere storage of isolated items.',
        derivation='It follows from the project preference relation -> identity -> memory, where memory is downstream of identity.',
        implementation='Currently represented as a constitutive node; future work should bind it to explicit channels and attractor logic.',
        test='Verify topology presence and card availability; later test channel graphs and persistence semantics.',
        status='draft',
        interpretation='Memory is a tensioned structure, not a bag of disconnected facts.',
        docs=['docs/analogies/ANALOGY_REGISTRY.md', 'docs/OBJECT_CARDS.md'],
        crossrefs=['identity', 'agent', 'provenance'],
    ),
    'execution': ObjectCard(
        key='execution',
        title='Execution',
        role='Coordinate runtime movement, orchestration, and task progression.',
        definition='Execution is the dynamic layer that turns a prepared configuration into actual process flow.',
        derivation='It sits between constitutive formalism and interaction-level agent behavior.',
        implementation='Rendered in the orbital app with runtime config, kernel registry, and latest metrics.',
        test='Verify HTTP startup, execution panel rendering, and metrics presence.',
        status='runtime-only',
        interpretation='Execution is where the system stops describing motion and starts moving.',
        docs=['docs/REPORT_LOCAL_DEBUG_2026-03-25.md', 'docs/OBJECT_CARDS.md'],
        crossrefs=['kernel', 'planner', 'session_dynamics', 'command_routing'],
    ),
    'kernel': ObjectCard(
        key='kernel',
        title='Kernel',
        role='Provide the active computational engine for state updates.',
        definition='The kernel is the runtime engine that consumes configuration and performs operational state changes.',
        derivation='Execution depends on kernel availability but the kernel itself is still downstream of theory and constraints.',
        implementation='Backed by main.kernels.registry and surfaced in runtime config and event strip.',
        test='Check kernel registry rendering and launcher startup.',
        status='runtime-only',
        interpretation='The kernel turns system motion into work.',
        docs=['docs/analogies/ANALOGY_REGISTRY.md', 'docs/REPORT_LOCAL_DEBUG_2026-03-25.md'],
        crossrefs=['execution', 'operators', 'constants', 'agent'],
    ),
    'planner': ObjectCard(
        key='planner',
        title='Planner',
        role='Prepare ordered task movement across the cockpit.',
        definition='Planner is the future dynamic surface for sequencing actions, transitions, and work packages.',
        derivation='It is a child of execution because planning constrains motion before command routing fires.',
        implementation='Currently represented as a draft node in topology and rendered through object cards.',
        test='Verify child-node card rendering; later bind to real planning state.',
        status='draft',
        interpretation='Planner is the pre-motion geometry of execution.',
        docs=['docs/OBJECT_CARDS.md'],
        crossrefs=['execution', 'command_routing', 'agent'],
    ),
    'session_dynamics': ObjectCard(
        key='session_dynamics',
        title='Session Dynamics',
        role='Track temporal evolution of the current operational session.',
        definition='Session dynamics describe how active state changes over time during a run.',
        derivation='It sits under execution because runtime motion has temporal structure even when it is not yet fully modeled.',
        implementation='Draft node currently surfaced through the execution orbit and manifest.',
        test='Verify navigation and card rendering; later bind to state histories.',
        status='draft',
        interpretation='Session dynamics are the time-shape of execution.',
        docs=['docs/OBJECT_CARDS.md'],
        crossrefs=['execution', 'planner', 'memory_topology'],
    ),
    'command_routing': ObjectCard(
        key='command_routing',
        title='Command Routing',
        role='Map intent into executable pathways.',
        definition='Command routing turns planned or user-provided intent into concrete runtime branches.',
        derivation='It belongs under execution because it mediates between intent and actual action.',
        implementation='Draft node exposed in topology and current object-card layer.',
        test='Verify navigation and manifest export; later bind to routing traces.',
        status='draft',
        interpretation='Routing is the decision conduit from meaning to motion.',
        docs=['docs/OBJECT_CARDS.md'],
        crossrefs=['execution', 'planner', 'agent', 'tools'],
    ),
    'agent': ObjectCard(
        key='agent',
        title='Agent',
        role='Host chat, tools, and user-facing interaction pathways.',
        definition='The agent layer is the interaction shell through which the system meets inputs, outputs, and tools.',
        derivation='It is downstream of execution and kernel state, and upstream of files, models, and tool routing.',
        implementation='Rendered in the orbital app with shell status and legacy compatibility notes.',
        test='Verify agent workspace rendering and chat/tool visibility.',
        status='runtime-only',
        interpretation='The agent is not the whole system; it is the interaction face of a deeper architecture.',
        docs=['docs/OMEGA_COCKPIT_1_0.md', 'docs/OBJECT_CARDS.md'],
        crossrefs=['chat', 'tools', 'files', 'models', 'memory_topology'],
    ),
    'chat': ObjectCard(
        key='chat',
        title='Chat',
        role='Provide direct dialogue interaction inside the broader agent layer.',
        definition='Chat is the conversational surface, not the whole architecture.',
        derivation='It is a child of agent because conversation is only one mode of interaction.',
        implementation='Surfaced via the agent workspace and orbital navigation.',
        test='Verify agent-child card rendering and state selection.',
        status='runtime-only',
        interpretation='Chat is the visible mouth of the agent, not its whole body.',
        docs=['docs/OBJECT_CARDS.md'],
        crossrefs=['agent', 'tools', 'models'],
    ),
    'tools': ObjectCard(
        key='tools',
        title='Tool Interface',
        role='Expose external action adapters and instrument calls.',
        definition='Tools are the means by which the agent acts beyond plain text generation.',
        derivation='It is a child of agent because tools extend interaction into operations.',
        implementation='Currently draft, but already represented in topology and agent orbit.',
        test='Verify card rendering and navigation; later bind to invocation traces.',
        status='draft',
        interpretation='Tools are action-capable interfaces anchored to the agent layer.',
        docs=['docs/OBJECT_CARDS.md'],
        crossrefs=['agent', 'command_routing', 'chat'],
    ),
    'files': ObjectCard(
        key='files',
        title='Files',
        role='Expose local file interaction and working artifacts.',
        definition='Files are the local document and artifact surface used by the system during runtime.',
        derivation='A child of agent because user-facing work often passes through files before becoming evidence or export.',
        implementation='Rendered by the files/models workspace with local counts and tabular listing.',
        test='Verify count rendering and file listing.',
        status='runtime-only',
        interpretation='Files are the tactile document layer of the cockpit.',
        docs=['docs/OBJECT_CARDS.md'],
        crossrefs=['agent', 'evidence', 'boundary'],
    ),
    'models': ObjectCard(
        key='models',
        title='Models',
        role='Expose local model inventory and active model state.',
        definition='Models are the local inference resources available to the runtime and agent layers.',
        derivation='A child of agent because model choice shapes interaction quality but does not define cockpit architecture.',
        implementation='Rendered by the files/models workspace with GGUF counts and listing.',
        test='Verify model count rendering and active model visibility.',
        status='runtime-only',
        interpretation='Models are resources, not the center of the system.',
        docs=['docs/OBJECT_CARDS.md', 'docs/REPORT_LOCAL_DEBUG_2026-03-25.md'],
        crossrefs=['agent', 'chat', 'kernel'],
    ),
    'evidence': ObjectCard(
        key='evidence',
        title='Evidence',
        role='Expose logs, tests, audit, provenance, and diagnostics as epistemic pressure.',
        definition='Evidence is the observation layer that supports, weakens, or constrains system claims.',
        derivation='Evidence is distinct from theory and execution because it measures rather than merely declares or runs.',
        implementation='Rendered with log tails and epistemic state badges; linked to publication boundary by validation threads.',
        test='Check evidence workspace rendering and log accessibility.',
        status='runtime-only',
        interpretation='Evidence is the footprint trail that keeps the system honest.',
        docs=['docs/analogies/ANALOGY_REGISTRY.md', 'docs/REPORT_LOCAL_DEBUG_2026-03-25.md'],
        crossrefs=['observability', 'tests', 'audit', 'provenance', 'crossrefs', 'boundary'],
    ),
    'observability': ObjectCard(
        key='observability',
        title='Observability',
        role='Expose live metrics, logs, and runtime state traces.',
        definition='Observability is the operational visibility layer for what the system is doing now.',
        derivation='It is a child of evidence because metrics and logs are one evidence channel among several.',
        implementation='Currently represented via evidence workspace log tail and related runtime diagnostics.',
        test='Verify evidence rendering and availability of runtime log paths.',
        status='runtime-only',
        interpretation='Observability is the open instrument panel of the running system.',
        docs=['docs/REPORT_LOCAL_DEBUG_2026-03-25.md', 'docs/OBJECT_CARDS.md'],
        crossrefs=['evidence', 'audit', 'provenance'],
    ),
    'tests': ObjectCard(
        key='tests',
        title='Tests',
        role='Check behavioral and structural validity.',
        definition='Tests are executable validations that constrain whether nodes behave as claimed.',
        derivation='They belong under evidence because they measure actual behavior against expected behavior.',
        implementation='Currently surfaced as a child node and badge-level epistemic state.',
        test='Meta-test: ensure the test surface itself becomes bound to runnable checks over time.',
        status='provisional',
        interpretation='Tests are where claims meet executable friction.',
        docs=['docs/REPORT_LOCAL_DEBUG_2026-03-25.md', 'docs/OBJECT_CARDS.md'],
        crossrefs=['evidence', 'constraints', 'audit'],
    ),
    'audit': ObjectCard(
        key='audit',
        title='Audit',
        role='Provide trace review and integrity checking across runs.',
        definition='Audit is the layer that reviews what happened and whether it stayed within declared bounds.',
        derivation='Audit is evidence with historical and integrity emphasis rather than live metrics emphasis.',
        implementation='Currently draft, represented as a child of evidence and exported through topology and manifest.',
        test='Verify child-node card rendering; later bind to actual audit trail records.',
        status='draft',
        interpretation='Audit is retrospective epistemic discipline.',
        docs=['docs/REPORT_LOCAL_DEBUG_2026-03-25.md', 'docs/OBJECT_CARDS.md'],
        crossrefs=['evidence', 'observability', 'boundary', 'provenance'],
    ),
    'provenance': ObjectCard(
        key='provenance',
        title='Provenance',
        role='Track lineage and source-of-truth pathways.',
        definition='Provenance records where a statement, artifact, or state came from and how it moved.',
        derivation='It belongs under evidence because traceability is an epistemic condition, not just storage metadata.',
        implementation='Currently draft, but represented in topology, inspector, and manifest export.',
        test='Verify child-node card rendering; later bind to concrete artifact lineages.',
        status='draft',
        interpretation='Provenance is the memory of origin.',
        docs=['docs/OBJECT_CARDS.md'],
        crossrefs=['evidence', 'audit', 'files', 'crossrefs'],
    ),
    'crossrefs': ObjectCard(
        key='crossrefs',
        title='Crossrefs',
        role='Connect formal, documentary, and runtime objects into a readable network.',
        definition='Crossrefs are explicit links between nodes, docs, implementations, and interpretations.',
        derivation='They emerge naturally once nodes become explicit objects rather than loose labels.',
        implementation='Currently draft, but already reflected by object-card crossrefs, docs links, and white-thread relations.',
        test='Verify object-card crossrefs and inspector visibility; later bind to navigable references.',
        status='draft',
        interpretation='Crossrefs make the system legible as a network rather than a list.',
        docs=['docs/OBJECT_CARDS.md', 'docs/INDEX.md'],
        crossrefs=['theory', 'evidence', 'provenance', 'analogies'],
    ),
    'boundary': ObjectCard(
        key='boundary',
        title='Publication Boundary',
        role='Separate internal state from external release and publication surfaces.',
        definition='The publication boundary decides what remains private, what is exported, and what is fit for public release.',
        derivation='It is required by the project split between private canon, public theory export, and runtime demo surfaces.',
        implementation='Rendered in the orbital app with visibility classes and future sanitization placeholders.',
        test='Verify boundary workspace rendering and export-state visibility.',
        status='private-only',
        interpretation='The boundary is a careful gate, not merely a wall.',
        docs=['docs/OMEGA_COCKPIT_1_0.md', 'docs/analogies/MNEMONIC_BOOK_FOR_KIDS.md'],
        crossrefs=['evidence', 'files', 'constraints', 'audit'],
    ),
    'analogies': ObjectCard(
        key='analogies',
        title='Analogies',
        role='Translate hard formal concepts into mnemonic images without replacing the formal layer.',
        definition='Analogies form an educational layer that supports teaching, memory, and public explanation.',
        derivation='They are downstream of theory and linked to agent and evidence as explanatory bridges.',
        implementation='Rendered in omega_orbital_app as an education orbit and exported through orbital_manifest_export.',
        test='Verify navigation, markdown rendering, and inspector payload for educational nodes.',
        status='public-exported',
        interpretation='Analogies are the pedagogical bridge between formalism and memory.',
        docs=['docs/analogies/README.md', 'docs/analogies/ANALOGY_REGISTRY.md'],
        crossrefs=['theory', 'agent', 'evidence', 'analogy_registry', 'truth_attractor_analogies', 'mnemonic_book'],
    ),
    'analogy_registry': ObjectCard(
        key='analogy_registry',
        title='Analogy Registry',
        role='Map formal concepts to mnemonic images and limits of comparison.',
        definition='The registry is a controlled lookup layer for analogy usage.',
        derivation='It is a child of analogies because education needs stable mappings, not free-floating metaphors.',
        implementation='Stored as docs/analogies/ANALOGY_REGISTRY.md and rendered in the education orbit.',
        test='Verify markdown rendering and inspector payload.',
        status='public-exported',
        interpretation='The registry keeps analogy usage disciplined.',
        docs=['docs/analogies/ANALOGY_REGISTRY.md', 'docs/OBJECT_CARDS.md'],
        crossrefs=['analogies', 'truth_attractor_analogies', 'mnemonic_book'],
    ),
    'truth_attractor_analogies': ObjectCard(
        key='truth_attractor_analogies',
        title='Truth Attractor Analogies',
        role='Explain truth as attractor and consensus as convergence through teaching images.',
        definition='This node holds the analogy set specifically for truth, nodes, white threads, and false consensus.',
        derivation='It emerges from the project claim that truth is primary and consensus is a visible shadow of convergence.',
        implementation='Stored as docs/analogies/TRUTH_ATTRACTOR_ANALOGIES.md and rendered in the education orbit.',
        test='Verify markdown rendering and child-node selection.',
        status='public-exported',
        interpretation='This is the pedagogical translation of the truth-attractor thesis.',
        docs=['docs/analogies/TRUTH_ATTRACTOR_ANALOGIES.md', 'docs/OBJECT_CARDS.md'],
        crossrefs=['analogies', 'analogy_registry', 'theory', 'identity'],
    ),
    'mnemonic_book': ObjectCard(
        key='mnemonic_book',
        title='Mnemonic Book For Kids',
        role='Provide a child-safe mnemonic route into Omega language.',
        definition='The mnemonic book translates hard concepts into persistent, memorable images for children and beginners.',
        derivation='It is a child of analogies because it is the most explicit pedagogical surface in the current repo.',
        implementation='Stored as docs/analogies/MNEMONIC_BOOK_FOR_KIDS.md and rendered in the education orbit.',
        test='Verify markdown rendering and education-node selection.',
        status='public-exported',
        interpretation='This is the memory-facing edge of the educational layer.',
        docs=['docs/analogies/MNEMONIC_BOOK_FOR_KIDS.md', 'docs/OBJECT_CARDS.md'],
        crossrefs=['analogies', 'analogy_registry', 'constraints', 'boundary'],
    ),
}


def get_object_card(key: str) -> Optional[Dict[str, object]]:
    card = OBJECT_CARDS.get(key)
    return None if card is None else card.to_dict()


def export_object_cards() -> Dict[str, Dict[str, object]]:
    return {key: card.to_dict() for key, card in OBJECT_CARDS.items()}
